# Default values for variables
SERVICEID ?= {{serviceID}}
Registry ?={{registry}}
REPO  ?= $(Registry)/$(SERVICEID)
TAG   ?= latest
IMAGE ?= $(REPO):$(TAG)
FLAVOR ?= {{flavor}}
ARCH ?= {{arch}}
USERNAME ?= {{user}}
DIR ?= /tmp/$(SERVICEID)
NAME ?= ic2_$(serviceID)
PORT ?= {{port}}
PORT1 ?= {{port1}}

run:
	docker run --privileged --rm -d  \
		-p $(PORT):80 -p $(PORT1):443 \
		-e USER=$(USERNAME) -e PASSWORD=ic2 \
		--name $(NAME) \
		$(IMAGE)